#!/usr/bin/env python3
"""
embed_shaders.py — Read GLSL .vert/.frag files and generate a C header.

Strips the #version line from each file (compositor prepends its own at runtime).
Outputs to the path given by --output, or src/overlay_shader_embed.h by default.
"""

import os
import re
import sys
import argparse

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

VARIANTS = [
    ("120",   "overlay_vertex_120",   "overlay_fragment_120"),
    ("130",   "overlay_vertex_130",   "overlay_fragment_130"),
    ("300_es","overlay_vertex_300_es","overlay_fragment_300_es"),
    ("410",   "overlay_vertex_410",   "overlay_fragment_410"),
]

def read_body(shader_dir, path):
    full = os.path.join(shader_dir, path)
    with open(full) as f:
        lines = f.readlines()
    body = []
    for line in lines:
        if not re.match(r'#\s*version\b', line):
            body.append(line)
    return ''.join(body).rstrip('\n')

def c_escape(s):
    return (s
        .replace('\\', '\\\\')
        .replace('"', '\\"')
        .replace('\n', '\\n"\n    "'))

def generate(output, shader_dir):
    lines = []
    lines.append("// Auto-generated by embed_shaders.py — do not edit")
    lines.append("#pragma once")
    lines.append("")

    for variant, vert_var, frag_var in VARIANTS:
        vert_path = f"overlay_{variant}.vert"
        frag_path = f"overlay_{variant}.frag"

        for path, var in [(vert_path, vert_var), (frag_path, frag_var)]:
            body = read_body(shader_dir, path)
            escaped = c_escape(body)
            lines.append(f'static const char *{var} =')
            lines.append(f'    "{escaped}";')
            lines.append("")

    os.makedirs(os.path.dirname(output) or '.', exist_ok=True)
    with open(output, 'w') as f:
        f.write('\n'.join(lines))
        f.write('\n')

    print(f"[embed_shaders] Generated {output}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', default='src/overlay_shader_embed.h')
    parser.add_argument('--shader-dir', default=os.path.join(PROJECT_DIR, 'shaders'))
    args = parser.parse_args()
    generate(args.output, args.shader_dir)
